# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,high=10,size=(3,3))
b = np.random.randint(0,high=10,size=(3,3))
c = np.random.randint(0,high=10,size=(3,3))

In [11]:
a.dot(b+c) == a.dot(b)+a.dot(c)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [12]:
a.dot(b.dot(c)) == (a.dot(b)).dot(c)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [13]:
#hmm; didnt get the correct answer
a.dot(b) == b.dot(a)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [17]:
# This works if matrix is made up of single vectors (i.e. [[1],[2],[3]] not [[1,1],[2,2],[3,3]])
a_t = a.transpose()
b_t = b.transpose()

a_t.dot(b) == b_t.dot(a)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [25]:
AdotB = a.dot(b)
AdotB.transpose() == b_t.dot(a_t)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 